//
// Created by Nikita Kruk on 2019-03-12.
//

#ifndef SPC2ODEINTEGRATION_VORTEXARRAYSSYSTEM_HPP
#define SPC2ODEINTEGRATION_VORTEXARRAYSSYSTEM_HPP

class VortexArraysSystem
{

};

#endif //SPC2ODEINTEGRATION_VORTEXARRAYSSYSTEM_HPP
